<title>Lyy-配置管理系统</title>

<link href="/<%=JGlobal.productName %>/_urc/lib/layui/css/layui.css" rel="stylesheet" />
<link href="/<%=JGlobal.productName %>/_urc/lib/animate/animate.min.css" rel="stylesheet" />
<link href="/<%=JGlobal.productName %>/_urc/lib/font-awesome-4.7.0/css/font-awesome.css" rel="stylesheet" />
<link href="/<%=JGlobal.productName %>/_urc/lib/winui/css/winui.css" rel="stylesheet" />